<?php
/**
 * @var UserModel $user
 */

use Quiz\Models\UserModel;

?>

<!DOCTYPE html>

<html>

<head>
	<title></title>

</head>

<body>
<div class="container">
	<h2 class="title">Testa uzdevums <?= $user->name ?></h2>
</div>

<div class="container">
	<form action="ajax/saveUser" method="POST" id="user-form">
		<label for="name">Name</label>
		<input class="form-control" id="name" type="text" name="name" placeholder="Ievadi savu vārdu" required>
		<select class="form-control" name="options" required>
			<option disabled selected value> -- Izvēlies testu --</option>
            <?php $quizes ?>
            <?php foreach ($quizes as $quiz) : ?>
				<option value="<?= $quiz->name; ?>">
                    <?= $quiz->name; ?>
				</option>
            <?php endforeach; ?>;
		</select>

		<div class="center">
			<button class="btn btn-primary" role="button" type="submit" name="save"> Sākt</button>
		</div>

	</form>
</div>

<script type="text/javascript" charset="utf-8">
    (function () {
        let form = document.querySelector('#user-form');
        form.addEventListener('submit', function (event) {
            event.preventDefault();
            let formData = new FormData;
            let inputs = form.querySelectorAll('input');
            for (let i = 0; i < inputs.length; i++) {
                formData.append(inputs[i].name, inputs[i].value);
            }
            let xhr = new XMLHttpRequest();
            xhr.open(form.method, form.action, true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    console.log(xhr.response);
                }
            };
            xhr.send(formData);
        });
    })();
</script>

</body>
</html>